### ISSUE TITLE
Initial Modeling Notes

### ISSUE THREAD

**Issue by dravesb** [matthewrw/LM_Project#2]
Leave any comments you may have about some pre CV models in the comment section.

**Comment by dravesb** [comment]
Interaction term ideas: 

- Summer:Rain
- DC:DMC 
- FFMCQuantile:DC
- FFMCQuantile:DMC
- FFMCQuantile:Temp 
- FFMCQuantile:Wind 
- FFMCQuantile:Rain 
- FFMCQuantile:RH
- Temperature:RH
- Wetness:RH

**Comment by dravesb** [comment]
FFMC Quantile should probably be used as a (transformed?) continuous covariate. Quantiles 3 - 10 all behave similarity while quantiles 1 and 2 are much much different. We should allow that skew to be modeled with the continuous covariate.

**Comment by matthewrw** [comment]
In the training set points 89 and 305 are problematic because of very high and 0 ISI respectively.
